name: vilmart
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  json_annotation: ^4.8.1
  flutter_adaptive_scaffold: ^0.1.4
  adaptive_layout: ^0.1.7
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^12.1.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  image_picker: ^1.0.4
  dropdown_button2: ^1.9.2
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  firebase_core: ^2.18.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_secure_storage: ^8.1.0
  excel: ^3.0.0
  path_provider: ^2.1.1
  file_picker: ^5.3.1
  animated_splash_screen: ^1.3.0
  razorpay_flutter: ^1.4.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3
  qr_code_tools: ^0.2.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: any
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Categories/
    - assets/images/Logo2.png
    - assets/images/ad.png
